[irc]
server = "irc.freenode.net"
useSSL = false
port = 6667
nick = "PokerBot"
channel = "#PokerBot"
commandPrefix = "."
verbose = true

[game]
startStash = 200
ante = 0
bigBlind = 5
spyCards = false
