[irc]
server = "irc.libera.chat"
port = 6667
# serverPassword = "abc123"
nick = "PokerBot"
channel = "#PokerBot"
# channelPassword = "abc123"
commandPrefix = "."
verbose = true

[game]
startStash = 200
# ante = 5
bigBlind = 5
